# Makefile.in generated by automake 1.16.1 from Makefile.am.
# src/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2018 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/bigbrother
pkgincludedir = $(includedir)/bigbrother
pkglibdir = $(libdir)/bigbrother
pkglibexecdir = $(libexecdir)/bigbrother
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
target_triplet = x86_64-unknown-linux-gnu
bin_PROGRAMS = bigbrother$(EXEEXT)
subdir = src
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(am__DIST_COMMON)
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_bigbrother_OBJECTS = bigbrother-main.$(OBJEXT) \
	bigbrother-globals.$(OBJEXT) bigbrother-semaphors.$(OBJEXT) \
	bigbrother-utilites.$(OBJEXT) bigbrother-modem.$(OBJEXT) \
	bigbrother-port.$(OBJEXT) bigbrother-portsettings.$(OBJEXT) \
	bigbrother-QueryMsg.$(OBJEXT) bigbrother-scada.$(OBJEXT) \
	bigbrother-device.$(OBJEXT) bigbrother-devicemodbus.$(OBJEXT) \
	bigbrother-deviceShunt.$(OBJEXT) \
	bigbrother-devicemodemstat.$(OBJEXT) \
	bigbrother-Din16Dout8.$(OBJEXT) \
	bigbrother-EngineModbus.$(OBJEXT) \
	bigbrother-EngineModbusRTU.$(OBJEXT) \
	bigbrother-EngineModbusTCP.$(OBJEXT) \
	bigbrother-EngineModbusTCPServer.$(OBJEXT) \
	bigbrother-parameter.$(OBJEXT) \
	bigbrother-parametermodbus.$(OBJEXT) \
	bigbrother-parametermodbusint.$(OBJEXT) \
	bigbrother-parametermodbusbool.$(OBJEXT) \
	bigbrother-parametermodbusenum.$(OBJEXT) \
	bigbrother-parametermodbusfile.$(OBJEXT) \
	bigbrother-KN24defs.$(OBJEXT) \
	bigbrother-ParameterModbusFileKN24.$(OBJEXT) \
	bigbrother-parametermodbusws.$(OBJEXT) \
	bigbrother-parametermodbusieee754.$(OBJEXT) \
	bigbrother-parametermodbusieee754array.$(OBJEXT) \
	bigbrother-parametermodbusieee754matrix.$(OBJEXT) \
	bigbrother-server.$(OBJEXT) bigbrother-curlwrapper.$(OBJEXT) \
	bigbrother-UMKA03utilites.$(OBJEXT) \
	bigbrother-PostToServer.$(OBJEXT) \
	bigbrother-DataTransfer.$(OBJEXT) \
	bigbrother-OverflowFile.$(OBJEXT) \
	bigbrother-ConfigFile.$(OBJEXT) \
	bigbrother-XMLAttribute.$(OBJEXT)
bigbrother_OBJECTS = $(am_bigbrother_OBJECTS)
bigbrother_DEPENDENCIES =
bigbrother_LINK = $(CXXLD) $(bigbrother_CXXFLAGS) $(CXXFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = ./$(DEPDIR)/bigbrother-ConfigFile.Po \
	./$(DEPDIR)/bigbrother-DataTransfer.Po \
	./$(DEPDIR)/bigbrother-Din16Dout8.Po \
	./$(DEPDIR)/bigbrother-EngineModbus.Po \
	./$(DEPDIR)/bigbrother-EngineModbusRTU.Po \
	./$(DEPDIR)/bigbrother-EngineModbusTCP.Po \
	./$(DEPDIR)/bigbrother-EngineModbusTCPServer.Po \
	./$(DEPDIR)/bigbrother-KN24defs.Po \
	./$(DEPDIR)/bigbrother-OverflowFile.Po \
	./$(DEPDIR)/bigbrother-ParameterModbusFileKN24.Po \
	./$(DEPDIR)/bigbrother-PostToServer.Po \
	./$(DEPDIR)/bigbrother-QueryMsg.Po \
	./$(DEPDIR)/bigbrother-UMKA03utilites.Po \
	./$(DEPDIR)/bigbrother-XMLAttribute.Po \
	./$(DEPDIR)/bigbrother-curlwrapper.Po \
	./$(DEPDIR)/bigbrother-device.Po \
	./$(DEPDIR)/bigbrother-deviceShunt.Po \
	./$(DEPDIR)/bigbrother-devicemodbus.Po \
	./$(DEPDIR)/bigbrother-devicemodemstat.Po \
	./$(DEPDIR)/bigbrother-globals.Po \
	./$(DEPDIR)/bigbrother-main.Po ./$(DEPDIR)/bigbrother-modem.Po \
	./$(DEPDIR)/bigbrother-parameter.Po \
	./$(DEPDIR)/bigbrother-parametermodbus.Po \
	./$(DEPDIR)/bigbrother-parametermodbusbool.Po \
	./$(DEPDIR)/bigbrother-parametermodbusenum.Po \
	./$(DEPDIR)/bigbrother-parametermodbusfile.Po \
	./$(DEPDIR)/bigbrother-parametermodbusieee754.Po \
	./$(DEPDIR)/bigbrother-parametermodbusieee754array.Po \
	./$(DEPDIR)/bigbrother-parametermodbusieee754matrix.Po \
	./$(DEPDIR)/bigbrother-parametermodbusint.Po \
	./$(DEPDIR)/bigbrother-parametermodbusws.Po \
	./$(DEPDIR)/bigbrother-port.Po \
	./$(DEPDIR)/bigbrother-portsettings.Po \
	./$(DEPDIR)/bigbrother-scada.Po \
	./$(DEPDIR)/bigbrother-semaphors.Po \
	./$(DEPDIR)/bigbrother-server.Po \
	./$(DEPDIR)/bigbrother-utilites.Po
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(bigbrother_SOURCES)
DIST_SOURCES = $(bigbrother_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
am__DIST_COMMON = $(srcdir)/Makefile.in $(top_srcdir)/depcomp
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = aclocal-1.16
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = autoconf
AUTOHEADER = autoheader
AUTOMAKE = automake-1.16
AWK = gawk
BIGBROTHER_CFLAGS = -I/usr/local/include/modbus -I/usr/local/include/serialv -I/usr/include/libxml++-2.6 -I/usr/lib/x86_64-linux-gnu/libxml++-2.6/include -I/usr/include/libxml2 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/x86_64-linux-gnu
BIGBROTHER_LIBS = -L/usr/local/lib -lxml++-2.6 -lxml2 -lglibmm-2.4 -lgobject-2.0 -lglib-2.0 -lsigc-2.0 -lmodbus -lserialv -lcurl -lcrypto
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2 -pthread -std=c++11 -Wno-deprecated 
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"bigbrother\" -DPACKAGE_TARNAME=\"bigbrother\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"bigbrother\ 1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"bigbrother\" -DVERSION=\"1.0\"
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EXEEXT = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = bigbrother
PACKAGE_BUGREPORT = 
PACKAGE_NAME = bigbrother
PACKAGE_STRING = bigbrother 1.0
PACKAGE_TARNAME = bigbrother
PACKAGE_URL = 
PACKAGE_VERSION = 1.0
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 1.0
abs_builddir = /home/v7r/projects/MT01/bigbrother/src
abs_srcdir = /home/v7r/projects/MT01/bigbrother/src
abs_top_builddir = /home/v7r/projects/MT01/bigbrother
abs_top_srcdir = /home/v7r/projects/MT01/bigbrother
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/v7r/projects/MT01/bigbrother/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target = x86_64-unknown-linux-gnu
target_alias = 
target_cpu = x86_64
target_os = linux-gnu
target_vendor = unknown
top_build_prefix = ../
top_builddir = ..
top_srcdir = ..
bigbrother_SOURCES = main.cpp \
					globals.h globals.cpp \
					semaphors.h semaphors.cpp \
					utilites.h utilites.cpp \
					modem.h modem.cpp \
					port.h port.cpp \
                    portsettings.h portsettings.cpp \
					QueryMsg.h QueryMsg.cpp \
					scada.h scada.cpp \
					device.h device.cpp \
					devicemodbus.h devicemodbus.cpp \
                    deviceShunt.h deviceShunt.cpp \
					devicemodemstat.h devicemodemstat.cpp \
					Din16Dout8.h Din16Dout8.cpp \
					EngineModbus.h EngineModbus.cpp EngineModbusRTU.cpp EngineModbusTCP.cpp EngineModbusTCPServer.cpp \
					parameter.h parameter.cpp \
					parametermodbus.h parametermodbus.cpp \
					parametermodbusint.h parametermodbusint.cpp \
					parametermodbusbool.h parametermodbusbool.cpp \
					parametermodbusenum.h parametermodbusenum.cpp \
					parametermodbusfile.h parametermodbusfile.cpp \
					KN24defs.h KN24defs.cpp \
					ParameterModbusFileKN24.h ParameterModbusFileKN24.cpp \
					parametermodbusws.h parametermodbusws.cpp \
					parametermodbusieee754.h parametermodbusieee754.cpp parametermodbusieee754array.cpp parametermodbusieee754matrix.cpp \
					server.h server.cpp \
                                        curlwrapper.h curlwrapper.cpp \
					UMKA03utilites.h UMKA03utilites.cpp \
					PostToServer.h PostToServer.cpp \
					DataTransfer.h DataTransfer.cpp \
					OverflowFile.h OverflowFile.cpp \
					ConfigFile.h ConfigFile.cpp \
					XMLAttribute.h XMLAttribute.cpp

bigbrother_CPPFLAGS = -I/usr/local/include/modbus -I/usr/local/include/serialv -I/usr/include/libxml++-2.6 -I/usr/lib/x86_64-linux-gnu/libxml++-2.6/include -I/usr/include/libxml2 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/x86_64-linux-gnu
bigbrother_CXXFLAGS = -I/usr/local/include/modbus -I/usr/local/include/serialv -I/usr/include/libxml++-2.6 -I/usr/lib/x86_64-linux-gnu/libxml++-2.6/include -I/usr/include/libxml2 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/x86_64-linux-gnu
bigbrother_LDADD = -L/usr/local/lib -lxml++-2.6 -lxml2 -lglibmm-2.4 -lgobject-2.0 -lglib-2.0 -lsigc-2.0 -lmodbus -lserialv -lcurl -lcrypto
all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu src/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu src/Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

bigbrother$(EXEEXT): $(bigbrother_OBJECTS) $(bigbrother_DEPENDENCIES) $(EXTRA_bigbrother_DEPENDENCIES) 
	@rm -f bigbrother$(EXEEXT)
	$(AM_V_CXXLD)$(bigbrother_LINK) $(bigbrother_OBJECTS) $(bigbrother_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/bigbrother-ConfigFile.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-DataTransfer.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-Din16Dout8.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-EngineModbus.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-EngineModbusRTU.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-EngineModbusTCP.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-EngineModbusTCPServer.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-KN24defs.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-OverflowFile.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-ParameterModbusFileKN24.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-PostToServer.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-QueryMsg.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-UMKA03utilites.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-XMLAttribute.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-curlwrapper.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-device.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-deviceShunt.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-devicemodbus.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-devicemodemstat.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-globals.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-main.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-modem.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-parameter.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-parametermodbus.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-parametermodbusbool.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-parametermodbusenum.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-parametermodbusfile.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-parametermodbusieee754.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-parametermodbusieee754array.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-parametermodbusieee754matrix.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-parametermodbusint.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-parametermodbusws.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-port.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-portsettings.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-scada.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-semaphors.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-server.Po # am--include-marker
include ./$(DEPDIR)/bigbrother-utilites.Po # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@echo '# dummy' >$@-t && $(am__mv) $@-t $@

am--depfiles: $(am__depfiles_remade)

.cpp.o:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

bigbrother-main.o: main.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-main.o -MD -MP -MF $(DEPDIR)/bigbrother-main.Tpo -c -o bigbrother-main.o `test -f 'main.cpp' || echo '$(srcdir)/'`main.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-main.Tpo $(DEPDIR)/bigbrother-main.Po
#	$(AM_V_CXX)source='main.cpp' object='bigbrother-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-main.o `test -f 'main.cpp' || echo '$(srcdir)/'`main.cpp

bigbrother-main.obj: main.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-main.obj -MD -MP -MF $(DEPDIR)/bigbrother-main.Tpo -c -o bigbrother-main.obj `if test -f 'main.cpp'; then $(CYGPATH_W) 'main.cpp'; else $(CYGPATH_W) '$(srcdir)/main.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-main.Tpo $(DEPDIR)/bigbrother-main.Po
#	$(AM_V_CXX)source='main.cpp' object='bigbrother-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-main.obj `if test -f 'main.cpp'; then $(CYGPATH_W) 'main.cpp'; else $(CYGPATH_W) '$(srcdir)/main.cpp'; fi`

bigbrother-globals.o: globals.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-globals.o -MD -MP -MF $(DEPDIR)/bigbrother-globals.Tpo -c -o bigbrother-globals.o `test -f 'globals.cpp' || echo '$(srcdir)/'`globals.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-globals.Tpo $(DEPDIR)/bigbrother-globals.Po
#	$(AM_V_CXX)source='globals.cpp' object='bigbrother-globals.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-globals.o `test -f 'globals.cpp' || echo '$(srcdir)/'`globals.cpp

bigbrother-globals.obj: globals.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-globals.obj -MD -MP -MF $(DEPDIR)/bigbrother-globals.Tpo -c -o bigbrother-globals.obj `if test -f 'globals.cpp'; then $(CYGPATH_W) 'globals.cpp'; else $(CYGPATH_W) '$(srcdir)/globals.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-globals.Tpo $(DEPDIR)/bigbrother-globals.Po
#	$(AM_V_CXX)source='globals.cpp' object='bigbrother-globals.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-globals.obj `if test -f 'globals.cpp'; then $(CYGPATH_W) 'globals.cpp'; else $(CYGPATH_W) '$(srcdir)/globals.cpp'; fi`

bigbrother-semaphors.o: semaphors.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-semaphors.o -MD -MP -MF $(DEPDIR)/bigbrother-semaphors.Tpo -c -o bigbrother-semaphors.o `test -f 'semaphors.cpp' || echo '$(srcdir)/'`semaphors.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-semaphors.Tpo $(DEPDIR)/bigbrother-semaphors.Po
#	$(AM_V_CXX)source='semaphors.cpp' object='bigbrother-semaphors.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-semaphors.o `test -f 'semaphors.cpp' || echo '$(srcdir)/'`semaphors.cpp

bigbrother-semaphors.obj: semaphors.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-semaphors.obj -MD -MP -MF $(DEPDIR)/bigbrother-semaphors.Tpo -c -o bigbrother-semaphors.obj `if test -f 'semaphors.cpp'; then $(CYGPATH_W) 'semaphors.cpp'; else $(CYGPATH_W) '$(srcdir)/semaphors.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-semaphors.Tpo $(DEPDIR)/bigbrother-semaphors.Po
#	$(AM_V_CXX)source='semaphors.cpp' object='bigbrother-semaphors.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-semaphors.obj `if test -f 'semaphors.cpp'; then $(CYGPATH_W) 'semaphors.cpp'; else $(CYGPATH_W) '$(srcdir)/semaphors.cpp'; fi`

bigbrother-utilites.o: utilites.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-utilites.o -MD -MP -MF $(DEPDIR)/bigbrother-utilites.Tpo -c -o bigbrother-utilites.o `test -f 'utilites.cpp' || echo '$(srcdir)/'`utilites.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-utilites.Tpo $(DEPDIR)/bigbrother-utilites.Po
#	$(AM_V_CXX)source='utilites.cpp' object='bigbrother-utilites.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-utilites.o `test -f 'utilites.cpp' || echo '$(srcdir)/'`utilites.cpp

bigbrother-utilites.obj: utilites.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-utilites.obj -MD -MP -MF $(DEPDIR)/bigbrother-utilites.Tpo -c -o bigbrother-utilites.obj `if test -f 'utilites.cpp'; then $(CYGPATH_W) 'utilites.cpp'; else $(CYGPATH_W) '$(srcdir)/utilites.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-utilites.Tpo $(DEPDIR)/bigbrother-utilites.Po
#	$(AM_V_CXX)source='utilites.cpp' object='bigbrother-utilites.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-utilites.obj `if test -f 'utilites.cpp'; then $(CYGPATH_W) 'utilites.cpp'; else $(CYGPATH_W) '$(srcdir)/utilites.cpp'; fi`

bigbrother-modem.o: modem.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-modem.o -MD -MP -MF $(DEPDIR)/bigbrother-modem.Tpo -c -o bigbrother-modem.o `test -f 'modem.cpp' || echo '$(srcdir)/'`modem.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-modem.Tpo $(DEPDIR)/bigbrother-modem.Po
#	$(AM_V_CXX)source='modem.cpp' object='bigbrother-modem.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-modem.o `test -f 'modem.cpp' || echo '$(srcdir)/'`modem.cpp

bigbrother-modem.obj: modem.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-modem.obj -MD -MP -MF $(DEPDIR)/bigbrother-modem.Tpo -c -o bigbrother-modem.obj `if test -f 'modem.cpp'; then $(CYGPATH_W) 'modem.cpp'; else $(CYGPATH_W) '$(srcdir)/modem.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-modem.Tpo $(DEPDIR)/bigbrother-modem.Po
#	$(AM_V_CXX)source='modem.cpp' object='bigbrother-modem.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-modem.obj `if test -f 'modem.cpp'; then $(CYGPATH_W) 'modem.cpp'; else $(CYGPATH_W) '$(srcdir)/modem.cpp'; fi`

bigbrother-port.o: port.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-port.o -MD -MP -MF $(DEPDIR)/bigbrother-port.Tpo -c -o bigbrother-port.o `test -f 'port.cpp' || echo '$(srcdir)/'`port.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-port.Tpo $(DEPDIR)/bigbrother-port.Po
#	$(AM_V_CXX)source='port.cpp' object='bigbrother-port.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-port.o `test -f 'port.cpp' || echo '$(srcdir)/'`port.cpp

bigbrother-port.obj: port.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-port.obj -MD -MP -MF $(DEPDIR)/bigbrother-port.Tpo -c -o bigbrother-port.obj `if test -f 'port.cpp'; then $(CYGPATH_W) 'port.cpp'; else $(CYGPATH_W) '$(srcdir)/port.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-port.Tpo $(DEPDIR)/bigbrother-port.Po
#	$(AM_V_CXX)source='port.cpp' object='bigbrother-port.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-port.obj `if test -f 'port.cpp'; then $(CYGPATH_W) 'port.cpp'; else $(CYGPATH_W) '$(srcdir)/port.cpp'; fi`

bigbrother-portsettings.o: portsettings.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-portsettings.o -MD -MP -MF $(DEPDIR)/bigbrother-portsettings.Tpo -c -o bigbrother-portsettings.o `test -f 'portsettings.cpp' || echo '$(srcdir)/'`portsettings.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-portsettings.Tpo $(DEPDIR)/bigbrother-portsettings.Po
#	$(AM_V_CXX)source='portsettings.cpp' object='bigbrother-portsettings.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-portsettings.o `test -f 'portsettings.cpp' || echo '$(srcdir)/'`portsettings.cpp

bigbrother-portsettings.obj: portsettings.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-portsettings.obj -MD -MP -MF $(DEPDIR)/bigbrother-portsettings.Tpo -c -o bigbrother-portsettings.obj `if test -f 'portsettings.cpp'; then $(CYGPATH_W) 'portsettings.cpp'; else $(CYGPATH_W) '$(srcdir)/portsettings.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-portsettings.Tpo $(DEPDIR)/bigbrother-portsettings.Po
#	$(AM_V_CXX)source='portsettings.cpp' object='bigbrother-portsettings.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-portsettings.obj `if test -f 'portsettings.cpp'; then $(CYGPATH_W) 'portsettings.cpp'; else $(CYGPATH_W) '$(srcdir)/portsettings.cpp'; fi`

bigbrother-QueryMsg.o: QueryMsg.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-QueryMsg.o -MD -MP -MF $(DEPDIR)/bigbrother-QueryMsg.Tpo -c -o bigbrother-QueryMsg.o `test -f 'QueryMsg.cpp' || echo '$(srcdir)/'`QueryMsg.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-QueryMsg.Tpo $(DEPDIR)/bigbrother-QueryMsg.Po
#	$(AM_V_CXX)source='QueryMsg.cpp' object='bigbrother-QueryMsg.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-QueryMsg.o `test -f 'QueryMsg.cpp' || echo '$(srcdir)/'`QueryMsg.cpp

bigbrother-QueryMsg.obj: QueryMsg.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-QueryMsg.obj -MD -MP -MF $(DEPDIR)/bigbrother-QueryMsg.Tpo -c -o bigbrother-QueryMsg.obj `if test -f 'QueryMsg.cpp'; then $(CYGPATH_W) 'QueryMsg.cpp'; else $(CYGPATH_W) '$(srcdir)/QueryMsg.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-QueryMsg.Tpo $(DEPDIR)/bigbrother-QueryMsg.Po
#	$(AM_V_CXX)source='QueryMsg.cpp' object='bigbrother-QueryMsg.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-QueryMsg.obj `if test -f 'QueryMsg.cpp'; then $(CYGPATH_W) 'QueryMsg.cpp'; else $(CYGPATH_W) '$(srcdir)/QueryMsg.cpp'; fi`

bigbrother-scada.o: scada.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-scada.o -MD -MP -MF $(DEPDIR)/bigbrother-scada.Tpo -c -o bigbrother-scada.o `test -f 'scada.cpp' || echo '$(srcdir)/'`scada.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-scada.Tpo $(DEPDIR)/bigbrother-scada.Po
#	$(AM_V_CXX)source='scada.cpp' object='bigbrother-scada.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-scada.o `test -f 'scada.cpp' || echo '$(srcdir)/'`scada.cpp

bigbrother-scada.obj: scada.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-scada.obj -MD -MP -MF $(DEPDIR)/bigbrother-scada.Tpo -c -o bigbrother-scada.obj `if test -f 'scada.cpp'; then $(CYGPATH_W) 'scada.cpp'; else $(CYGPATH_W) '$(srcdir)/scada.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-scada.Tpo $(DEPDIR)/bigbrother-scada.Po
#	$(AM_V_CXX)source='scada.cpp' object='bigbrother-scada.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-scada.obj `if test -f 'scada.cpp'; then $(CYGPATH_W) 'scada.cpp'; else $(CYGPATH_W) '$(srcdir)/scada.cpp'; fi`

bigbrother-device.o: device.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-device.o -MD -MP -MF $(DEPDIR)/bigbrother-device.Tpo -c -o bigbrother-device.o `test -f 'device.cpp' || echo '$(srcdir)/'`device.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-device.Tpo $(DEPDIR)/bigbrother-device.Po
#	$(AM_V_CXX)source='device.cpp' object='bigbrother-device.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-device.o `test -f 'device.cpp' || echo '$(srcdir)/'`device.cpp

bigbrother-device.obj: device.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-device.obj -MD -MP -MF $(DEPDIR)/bigbrother-device.Tpo -c -o bigbrother-device.obj `if test -f 'device.cpp'; then $(CYGPATH_W) 'device.cpp'; else $(CYGPATH_W) '$(srcdir)/device.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-device.Tpo $(DEPDIR)/bigbrother-device.Po
#	$(AM_V_CXX)source='device.cpp' object='bigbrother-device.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-device.obj `if test -f 'device.cpp'; then $(CYGPATH_W) 'device.cpp'; else $(CYGPATH_W) '$(srcdir)/device.cpp'; fi`

bigbrother-devicemodbus.o: devicemodbus.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-devicemodbus.o -MD -MP -MF $(DEPDIR)/bigbrother-devicemodbus.Tpo -c -o bigbrother-devicemodbus.o `test -f 'devicemodbus.cpp' || echo '$(srcdir)/'`devicemodbus.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-devicemodbus.Tpo $(DEPDIR)/bigbrother-devicemodbus.Po
#	$(AM_V_CXX)source='devicemodbus.cpp' object='bigbrother-devicemodbus.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-devicemodbus.o `test -f 'devicemodbus.cpp' || echo '$(srcdir)/'`devicemodbus.cpp

bigbrother-devicemodbus.obj: devicemodbus.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-devicemodbus.obj -MD -MP -MF $(DEPDIR)/bigbrother-devicemodbus.Tpo -c -o bigbrother-devicemodbus.obj `if test -f 'devicemodbus.cpp'; then $(CYGPATH_W) 'devicemodbus.cpp'; else $(CYGPATH_W) '$(srcdir)/devicemodbus.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-devicemodbus.Tpo $(DEPDIR)/bigbrother-devicemodbus.Po
#	$(AM_V_CXX)source='devicemodbus.cpp' object='bigbrother-devicemodbus.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-devicemodbus.obj `if test -f 'devicemodbus.cpp'; then $(CYGPATH_W) 'devicemodbus.cpp'; else $(CYGPATH_W) '$(srcdir)/devicemodbus.cpp'; fi`

bigbrother-deviceShunt.o: deviceShunt.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-deviceShunt.o -MD -MP -MF $(DEPDIR)/bigbrother-deviceShunt.Tpo -c -o bigbrother-deviceShunt.o `test -f 'deviceShunt.cpp' || echo '$(srcdir)/'`deviceShunt.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-deviceShunt.Tpo $(DEPDIR)/bigbrother-deviceShunt.Po
#	$(AM_V_CXX)source='deviceShunt.cpp' object='bigbrother-deviceShunt.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-deviceShunt.o `test -f 'deviceShunt.cpp' || echo '$(srcdir)/'`deviceShunt.cpp

bigbrother-deviceShunt.obj: deviceShunt.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-deviceShunt.obj -MD -MP -MF $(DEPDIR)/bigbrother-deviceShunt.Tpo -c -o bigbrother-deviceShunt.obj `if test -f 'deviceShunt.cpp'; then $(CYGPATH_W) 'deviceShunt.cpp'; else $(CYGPATH_W) '$(srcdir)/deviceShunt.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-deviceShunt.Tpo $(DEPDIR)/bigbrother-deviceShunt.Po
#	$(AM_V_CXX)source='deviceShunt.cpp' object='bigbrother-deviceShunt.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-deviceShunt.obj `if test -f 'deviceShunt.cpp'; then $(CYGPATH_W) 'deviceShunt.cpp'; else $(CYGPATH_W) '$(srcdir)/deviceShunt.cpp'; fi`

bigbrother-devicemodemstat.o: devicemodemstat.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-devicemodemstat.o -MD -MP -MF $(DEPDIR)/bigbrother-devicemodemstat.Tpo -c -o bigbrother-devicemodemstat.o `test -f 'devicemodemstat.cpp' || echo '$(srcdir)/'`devicemodemstat.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-devicemodemstat.Tpo $(DEPDIR)/bigbrother-devicemodemstat.Po
#	$(AM_V_CXX)source='devicemodemstat.cpp' object='bigbrother-devicemodemstat.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-devicemodemstat.o `test -f 'devicemodemstat.cpp' || echo '$(srcdir)/'`devicemodemstat.cpp

bigbrother-devicemodemstat.obj: devicemodemstat.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-devicemodemstat.obj -MD -MP -MF $(DEPDIR)/bigbrother-devicemodemstat.Tpo -c -o bigbrother-devicemodemstat.obj `if test -f 'devicemodemstat.cpp'; then $(CYGPATH_W) 'devicemodemstat.cpp'; else $(CYGPATH_W) '$(srcdir)/devicemodemstat.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-devicemodemstat.Tpo $(DEPDIR)/bigbrother-devicemodemstat.Po
#	$(AM_V_CXX)source='devicemodemstat.cpp' object='bigbrother-devicemodemstat.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-devicemodemstat.obj `if test -f 'devicemodemstat.cpp'; then $(CYGPATH_W) 'devicemodemstat.cpp'; else $(CYGPATH_W) '$(srcdir)/devicemodemstat.cpp'; fi`

bigbrother-Din16Dout8.o: Din16Dout8.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-Din16Dout8.o -MD -MP -MF $(DEPDIR)/bigbrother-Din16Dout8.Tpo -c -o bigbrother-Din16Dout8.o `test -f 'Din16Dout8.cpp' || echo '$(srcdir)/'`Din16Dout8.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-Din16Dout8.Tpo $(DEPDIR)/bigbrother-Din16Dout8.Po
#	$(AM_V_CXX)source='Din16Dout8.cpp' object='bigbrother-Din16Dout8.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-Din16Dout8.o `test -f 'Din16Dout8.cpp' || echo '$(srcdir)/'`Din16Dout8.cpp

bigbrother-Din16Dout8.obj: Din16Dout8.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-Din16Dout8.obj -MD -MP -MF $(DEPDIR)/bigbrother-Din16Dout8.Tpo -c -o bigbrother-Din16Dout8.obj `if test -f 'Din16Dout8.cpp'; then $(CYGPATH_W) 'Din16Dout8.cpp'; else $(CYGPATH_W) '$(srcdir)/Din16Dout8.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-Din16Dout8.Tpo $(DEPDIR)/bigbrother-Din16Dout8.Po
#	$(AM_V_CXX)source='Din16Dout8.cpp' object='bigbrother-Din16Dout8.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-Din16Dout8.obj `if test -f 'Din16Dout8.cpp'; then $(CYGPATH_W) 'Din16Dout8.cpp'; else $(CYGPATH_W) '$(srcdir)/Din16Dout8.cpp'; fi`

bigbrother-EngineModbus.o: EngineModbus.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-EngineModbus.o -MD -MP -MF $(DEPDIR)/bigbrother-EngineModbus.Tpo -c -o bigbrother-EngineModbus.o `test -f 'EngineModbus.cpp' || echo '$(srcdir)/'`EngineModbus.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-EngineModbus.Tpo $(DEPDIR)/bigbrother-EngineModbus.Po
#	$(AM_V_CXX)source='EngineModbus.cpp' object='bigbrother-EngineModbus.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-EngineModbus.o `test -f 'EngineModbus.cpp' || echo '$(srcdir)/'`EngineModbus.cpp

bigbrother-EngineModbus.obj: EngineModbus.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-EngineModbus.obj -MD -MP -MF $(DEPDIR)/bigbrother-EngineModbus.Tpo -c -o bigbrother-EngineModbus.obj `if test -f 'EngineModbus.cpp'; then $(CYGPATH_W) 'EngineModbus.cpp'; else $(CYGPATH_W) '$(srcdir)/EngineModbus.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-EngineModbus.Tpo $(DEPDIR)/bigbrother-EngineModbus.Po
#	$(AM_V_CXX)source='EngineModbus.cpp' object='bigbrother-EngineModbus.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-EngineModbus.obj `if test -f 'EngineModbus.cpp'; then $(CYGPATH_W) 'EngineModbus.cpp'; else $(CYGPATH_W) '$(srcdir)/EngineModbus.cpp'; fi`

bigbrother-EngineModbusRTU.o: EngineModbusRTU.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-EngineModbusRTU.o -MD -MP -MF $(DEPDIR)/bigbrother-EngineModbusRTU.Tpo -c -o bigbrother-EngineModbusRTU.o `test -f 'EngineModbusRTU.cpp' || echo '$(srcdir)/'`EngineModbusRTU.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-EngineModbusRTU.Tpo $(DEPDIR)/bigbrother-EngineModbusRTU.Po
#	$(AM_V_CXX)source='EngineModbusRTU.cpp' object='bigbrother-EngineModbusRTU.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-EngineModbusRTU.o `test -f 'EngineModbusRTU.cpp' || echo '$(srcdir)/'`EngineModbusRTU.cpp

bigbrother-EngineModbusRTU.obj: EngineModbusRTU.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-EngineModbusRTU.obj -MD -MP -MF $(DEPDIR)/bigbrother-EngineModbusRTU.Tpo -c -o bigbrother-EngineModbusRTU.obj `if test -f 'EngineModbusRTU.cpp'; then $(CYGPATH_W) 'EngineModbusRTU.cpp'; else $(CYGPATH_W) '$(srcdir)/EngineModbusRTU.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-EngineModbusRTU.Tpo $(DEPDIR)/bigbrother-EngineModbusRTU.Po
#	$(AM_V_CXX)source='EngineModbusRTU.cpp' object='bigbrother-EngineModbusRTU.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-EngineModbusRTU.obj `if test -f 'EngineModbusRTU.cpp'; then $(CYGPATH_W) 'EngineModbusRTU.cpp'; else $(CYGPATH_W) '$(srcdir)/EngineModbusRTU.cpp'; fi`

bigbrother-EngineModbusTCP.o: EngineModbusTCP.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-EngineModbusTCP.o -MD -MP -MF $(DEPDIR)/bigbrother-EngineModbusTCP.Tpo -c -o bigbrother-EngineModbusTCP.o `test -f 'EngineModbusTCP.cpp' || echo '$(srcdir)/'`EngineModbusTCP.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-EngineModbusTCP.Tpo $(DEPDIR)/bigbrother-EngineModbusTCP.Po
#	$(AM_V_CXX)source='EngineModbusTCP.cpp' object='bigbrother-EngineModbusTCP.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-EngineModbusTCP.o `test -f 'EngineModbusTCP.cpp' || echo '$(srcdir)/'`EngineModbusTCP.cpp

bigbrother-EngineModbusTCP.obj: EngineModbusTCP.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-EngineModbusTCP.obj -MD -MP -MF $(DEPDIR)/bigbrother-EngineModbusTCP.Tpo -c -o bigbrother-EngineModbusTCP.obj `if test -f 'EngineModbusTCP.cpp'; then $(CYGPATH_W) 'EngineModbusTCP.cpp'; else $(CYGPATH_W) '$(srcdir)/EngineModbusTCP.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-EngineModbusTCP.Tpo $(DEPDIR)/bigbrother-EngineModbusTCP.Po
#	$(AM_V_CXX)source='EngineModbusTCP.cpp' object='bigbrother-EngineModbusTCP.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-EngineModbusTCP.obj `if test -f 'EngineModbusTCP.cpp'; then $(CYGPATH_W) 'EngineModbusTCP.cpp'; else $(CYGPATH_W) '$(srcdir)/EngineModbusTCP.cpp'; fi`

bigbrother-EngineModbusTCPServer.o: EngineModbusTCPServer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-EngineModbusTCPServer.o -MD -MP -MF $(DEPDIR)/bigbrother-EngineModbusTCPServer.Tpo -c -o bigbrother-EngineModbusTCPServer.o `test -f 'EngineModbusTCPServer.cpp' || echo '$(srcdir)/'`EngineModbusTCPServer.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-EngineModbusTCPServer.Tpo $(DEPDIR)/bigbrother-EngineModbusTCPServer.Po
#	$(AM_V_CXX)source='EngineModbusTCPServer.cpp' object='bigbrother-EngineModbusTCPServer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-EngineModbusTCPServer.o `test -f 'EngineModbusTCPServer.cpp' || echo '$(srcdir)/'`EngineModbusTCPServer.cpp

bigbrother-EngineModbusTCPServer.obj: EngineModbusTCPServer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-EngineModbusTCPServer.obj -MD -MP -MF $(DEPDIR)/bigbrother-EngineModbusTCPServer.Tpo -c -o bigbrother-EngineModbusTCPServer.obj `if test -f 'EngineModbusTCPServer.cpp'; then $(CYGPATH_W) 'EngineModbusTCPServer.cpp'; else $(CYGPATH_W) '$(srcdir)/EngineModbusTCPServer.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-EngineModbusTCPServer.Tpo $(DEPDIR)/bigbrother-EngineModbusTCPServer.Po
#	$(AM_V_CXX)source='EngineModbusTCPServer.cpp' object='bigbrother-EngineModbusTCPServer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-EngineModbusTCPServer.obj `if test -f 'EngineModbusTCPServer.cpp'; then $(CYGPATH_W) 'EngineModbusTCPServer.cpp'; else $(CYGPATH_W) '$(srcdir)/EngineModbusTCPServer.cpp'; fi`

bigbrother-parameter.o: parameter.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parameter.o -MD -MP -MF $(DEPDIR)/bigbrother-parameter.Tpo -c -o bigbrother-parameter.o `test -f 'parameter.cpp' || echo '$(srcdir)/'`parameter.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parameter.Tpo $(DEPDIR)/bigbrother-parameter.Po
#	$(AM_V_CXX)source='parameter.cpp' object='bigbrother-parameter.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parameter.o `test -f 'parameter.cpp' || echo '$(srcdir)/'`parameter.cpp

bigbrother-parameter.obj: parameter.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parameter.obj -MD -MP -MF $(DEPDIR)/bigbrother-parameter.Tpo -c -o bigbrother-parameter.obj `if test -f 'parameter.cpp'; then $(CYGPATH_W) 'parameter.cpp'; else $(CYGPATH_W) '$(srcdir)/parameter.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parameter.Tpo $(DEPDIR)/bigbrother-parameter.Po
#	$(AM_V_CXX)source='parameter.cpp' object='bigbrother-parameter.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parameter.obj `if test -f 'parameter.cpp'; then $(CYGPATH_W) 'parameter.cpp'; else $(CYGPATH_W) '$(srcdir)/parameter.cpp'; fi`

bigbrother-parametermodbus.o: parametermodbus.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbus.o -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbus.Tpo -c -o bigbrother-parametermodbus.o `test -f 'parametermodbus.cpp' || echo '$(srcdir)/'`parametermodbus.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbus.Tpo $(DEPDIR)/bigbrother-parametermodbus.Po
#	$(AM_V_CXX)source='parametermodbus.cpp' object='bigbrother-parametermodbus.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbus.o `test -f 'parametermodbus.cpp' || echo '$(srcdir)/'`parametermodbus.cpp

bigbrother-parametermodbus.obj: parametermodbus.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbus.obj -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbus.Tpo -c -o bigbrother-parametermodbus.obj `if test -f 'parametermodbus.cpp'; then $(CYGPATH_W) 'parametermodbus.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbus.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbus.Tpo $(DEPDIR)/bigbrother-parametermodbus.Po
#	$(AM_V_CXX)source='parametermodbus.cpp' object='bigbrother-parametermodbus.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbus.obj `if test -f 'parametermodbus.cpp'; then $(CYGPATH_W) 'parametermodbus.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbus.cpp'; fi`

bigbrother-parametermodbusint.o: parametermodbusint.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbusint.o -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbusint.Tpo -c -o bigbrother-parametermodbusint.o `test -f 'parametermodbusint.cpp' || echo '$(srcdir)/'`parametermodbusint.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbusint.Tpo $(DEPDIR)/bigbrother-parametermodbusint.Po
#	$(AM_V_CXX)source='parametermodbusint.cpp' object='bigbrother-parametermodbusint.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbusint.o `test -f 'parametermodbusint.cpp' || echo '$(srcdir)/'`parametermodbusint.cpp

bigbrother-parametermodbusint.obj: parametermodbusint.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbusint.obj -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbusint.Tpo -c -o bigbrother-parametermodbusint.obj `if test -f 'parametermodbusint.cpp'; then $(CYGPATH_W) 'parametermodbusint.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbusint.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbusint.Tpo $(DEPDIR)/bigbrother-parametermodbusint.Po
#	$(AM_V_CXX)source='parametermodbusint.cpp' object='bigbrother-parametermodbusint.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbusint.obj `if test -f 'parametermodbusint.cpp'; then $(CYGPATH_W) 'parametermodbusint.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbusint.cpp'; fi`

bigbrother-parametermodbusbool.o: parametermodbusbool.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbusbool.o -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbusbool.Tpo -c -o bigbrother-parametermodbusbool.o `test -f 'parametermodbusbool.cpp' || echo '$(srcdir)/'`parametermodbusbool.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbusbool.Tpo $(DEPDIR)/bigbrother-parametermodbusbool.Po
#	$(AM_V_CXX)source='parametermodbusbool.cpp' object='bigbrother-parametermodbusbool.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbusbool.o `test -f 'parametermodbusbool.cpp' || echo '$(srcdir)/'`parametermodbusbool.cpp

bigbrother-parametermodbusbool.obj: parametermodbusbool.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbusbool.obj -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbusbool.Tpo -c -o bigbrother-parametermodbusbool.obj `if test -f 'parametermodbusbool.cpp'; then $(CYGPATH_W) 'parametermodbusbool.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbusbool.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbusbool.Tpo $(DEPDIR)/bigbrother-parametermodbusbool.Po
#	$(AM_V_CXX)source='parametermodbusbool.cpp' object='bigbrother-parametermodbusbool.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbusbool.obj `if test -f 'parametermodbusbool.cpp'; then $(CYGPATH_W) 'parametermodbusbool.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbusbool.cpp'; fi`

bigbrother-parametermodbusenum.o: parametermodbusenum.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbusenum.o -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbusenum.Tpo -c -o bigbrother-parametermodbusenum.o `test -f 'parametermodbusenum.cpp' || echo '$(srcdir)/'`parametermodbusenum.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbusenum.Tpo $(DEPDIR)/bigbrother-parametermodbusenum.Po
#	$(AM_V_CXX)source='parametermodbusenum.cpp' object='bigbrother-parametermodbusenum.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbusenum.o `test -f 'parametermodbusenum.cpp' || echo '$(srcdir)/'`parametermodbusenum.cpp

bigbrother-parametermodbusenum.obj: parametermodbusenum.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbusenum.obj -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbusenum.Tpo -c -o bigbrother-parametermodbusenum.obj `if test -f 'parametermodbusenum.cpp'; then $(CYGPATH_W) 'parametermodbusenum.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbusenum.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbusenum.Tpo $(DEPDIR)/bigbrother-parametermodbusenum.Po
#	$(AM_V_CXX)source='parametermodbusenum.cpp' object='bigbrother-parametermodbusenum.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbusenum.obj `if test -f 'parametermodbusenum.cpp'; then $(CYGPATH_W) 'parametermodbusenum.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbusenum.cpp'; fi`

bigbrother-parametermodbusfile.o: parametermodbusfile.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbusfile.o -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbusfile.Tpo -c -o bigbrother-parametermodbusfile.o `test -f 'parametermodbusfile.cpp' || echo '$(srcdir)/'`parametermodbusfile.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbusfile.Tpo $(DEPDIR)/bigbrother-parametermodbusfile.Po
#	$(AM_V_CXX)source='parametermodbusfile.cpp' object='bigbrother-parametermodbusfile.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbusfile.o `test -f 'parametermodbusfile.cpp' || echo '$(srcdir)/'`parametermodbusfile.cpp

bigbrother-parametermodbusfile.obj: parametermodbusfile.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbusfile.obj -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbusfile.Tpo -c -o bigbrother-parametermodbusfile.obj `if test -f 'parametermodbusfile.cpp'; then $(CYGPATH_W) 'parametermodbusfile.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbusfile.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbusfile.Tpo $(DEPDIR)/bigbrother-parametermodbusfile.Po
#	$(AM_V_CXX)source='parametermodbusfile.cpp' object='bigbrother-parametermodbusfile.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbusfile.obj `if test -f 'parametermodbusfile.cpp'; then $(CYGPATH_W) 'parametermodbusfile.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbusfile.cpp'; fi`

bigbrother-KN24defs.o: KN24defs.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-KN24defs.o -MD -MP -MF $(DEPDIR)/bigbrother-KN24defs.Tpo -c -o bigbrother-KN24defs.o `test -f 'KN24defs.cpp' || echo '$(srcdir)/'`KN24defs.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-KN24defs.Tpo $(DEPDIR)/bigbrother-KN24defs.Po
#	$(AM_V_CXX)source='KN24defs.cpp' object='bigbrother-KN24defs.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-KN24defs.o `test -f 'KN24defs.cpp' || echo '$(srcdir)/'`KN24defs.cpp

bigbrother-KN24defs.obj: KN24defs.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-KN24defs.obj -MD -MP -MF $(DEPDIR)/bigbrother-KN24defs.Tpo -c -o bigbrother-KN24defs.obj `if test -f 'KN24defs.cpp'; then $(CYGPATH_W) 'KN24defs.cpp'; else $(CYGPATH_W) '$(srcdir)/KN24defs.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-KN24defs.Tpo $(DEPDIR)/bigbrother-KN24defs.Po
#	$(AM_V_CXX)source='KN24defs.cpp' object='bigbrother-KN24defs.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-KN24defs.obj `if test -f 'KN24defs.cpp'; then $(CYGPATH_W) 'KN24defs.cpp'; else $(CYGPATH_W) '$(srcdir)/KN24defs.cpp'; fi`

bigbrother-ParameterModbusFileKN24.o: ParameterModbusFileKN24.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-ParameterModbusFileKN24.o -MD -MP -MF $(DEPDIR)/bigbrother-ParameterModbusFileKN24.Tpo -c -o bigbrother-ParameterModbusFileKN24.o `test -f 'ParameterModbusFileKN24.cpp' || echo '$(srcdir)/'`ParameterModbusFileKN24.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-ParameterModbusFileKN24.Tpo $(DEPDIR)/bigbrother-ParameterModbusFileKN24.Po
#	$(AM_V_CXX)source='ParameterModbusFileKN24.cpp' object='bigbrother-ParameterModbusFileKN24.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-ParameterModbusFileKN24.o `test -f 'ParameterModbusFileKN24.cpp' || echo '$(srcdir)/'`ParameterModbusFileKN24.cpp

bigbrother-ParameterModbusFileKN24.obj: ParameterModbusFileKN24.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-ParameterModbusFileKN24.obj -MD -MP -MF $(DEPDIR)/bigbrother-ParameterModbusFileKN24.Tpo -c -o bigbrother-ParameterModbusFileKN24.obj `if test -f 'ParameterModbusFileKN24.cpp'; then $(CYGPATH_W) 'ParameterModbusFileKN24.cpp'; else $(CYGPATH_W) '$(srcdir)/ParameterModbusFileKN24.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-ParameterModbusFileKN24.Tpo $(DEPDIR)/bigbrother-ParameterModbusFileKN24.Po
#	$(AM_V_CXX)source='ParameterModbusFileKN24.cpp' object='bigbrother-ParameterModbusFileKN24.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-ParameterModbusFileKN24.obj `if test -f 'ParameterModbusFileKN24.cpp'; then $(CYGPATH_W) 'ParameterModbusFileKN24.cpp'; else $(CYGPATH_W) '$(srcdir)/ParameterModbusFileKN24.cpp'; fi`

bigbrother-parametermodbusws.o: parametermodbusws.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbusws.o -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbusws.Tpo -c -o bigbrother-parametermodbusws.o `test -f 'parametermodbusws.cpp' || echo '$(srcdir)/'`parametermodbusws.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbusws.Tpo $(DEPDIR)/bigbrother-parametermodbusws.Po
#	$(AM_V_CXX)source='parametermodbusws.cpp' object='bigbrother-parametermodbusws.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbusws.o `test -f 'parametermodbusws.cpp' || echo '$(srcdir)/'`parametermodbusws.cpp

bigbrother-parametermodbusws.obj: parametermodbusws.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbusws.obj -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbusws.Tpo -c -o bigbrother-parametermodbusws.obj `if test -f 'parametermodbusws.cpp'; then $(CYGPATH_W) 'parametermodbusws.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbusws.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbusws.Tpo $(DEPDIR)/bigbrother-parametermodbusws.Po
#	$(AM_V_CXX)source='parametermodbusws.cpp' object='bigbrother-parametermodbusws.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbusws.obj `if test -f 'parametermodbusws.cpp'; then $(CYGPATH_W) 'parametermodbusws.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbusws.cpp'; fi`

bigbrother-parametermodbusieee754.o: parametermodbusieee754.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbusieee754.o -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbusieee754.Tpo -c -o bigbrother-parametermodbusieee754.o `test -f 'parametermodbusieee754.cpp' || echo '$(srcdir)/'`parametermodbusieee754.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbusieee754.Tpo $(DEPDIR)/bigbrother-parametermodbusieee754.Po
#	$(AM_V_CXX)source='parametermodbusieee754.cpp' object='bigbrother-parametermodbusieee754.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbusieee754.o `test -f 'parametermodbusieee754.cpp' || echo '$(srcdir)/'`parametermodbusieee754.cpp

bigbrother-parametermodbusieee754.obj: parametermodbusieee754.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbusieee754.obj -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbusieee754.Tpo -c -o bigbrother-parametermodbusieee754.obj `if test -f 'parametermodbusieee754.cpp'; then $(CYGPATH_W) 'parametermodbusieee754.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbusieee754.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbusieee754.Tpo $(DEPDIR)/bigbrother-parametermodbusieee754.Po
#	$(AM_V_CXX)source='parametermodbusieee754.cpp' object='bigbrother-parametermodbusieee754.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbusieee754.obj `if test -f 'parametermodbusieee754.cpp'; then $(CYGPATH_W) 'parametermodbusieee754.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbusieee754.cpp'; fi`

bigbrother-parametermodbusieee754array.o: parametermodbusieee754array.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbusieee754array.o -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbusieee754array.Tpo -c -o bigbrother-parametermodbusieee754array.o `test -f 'parametermodbusieee754array.cpp' || echo '$(srcdir)/'`parametermodbusieee754array.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbusieee754array.Tpo $(DEPDIR)/bigbrother-parametermodbusieee754array.Po
#	$(AM_V_CXX)source='parametermodbusieee754array.cpp' object='bigbrother-parametermodbusieee754array.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbusieee754array.o `test -f 'parametermodbusieee754array.cpp' || echo '$(srcdir)/'`parametermodbusieee754array.cpp

bigbrother-parametermodbusieee754array.obj: parametermodbusieee754array.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbusieee754array.obj -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbusieee754array.Tpo -c -o bigbrother-parametermodbusieee754array.obj `if test -f 'parametermodbusieee754array.cpp'; then $(CYGPATH_W) 'parametermodbusieee754array.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbusieee754array.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbusieee754array.Tpo $(DEPDIR)/bigbrother-parametermodbusieee754array.Po
#	$(AM_V_CXX)source='parametermodbusieee754array.cpp' object='bigbrother-parametermodbusieee754array.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbusieee754array.obj `if test -f 'parametermodbusieee754array.cpp'; then $(CYGPATH_W) 'parametermodbusieee754array.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbusieee754array.cpp'; fi`

bigbrother-parametermodbusieee754matrix.o: parametermodbusieee754matrix.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbusieee754matrix.o -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbusieee754matrix.Tpo -c -o bigbrother-parametermodbusieee754matrix.o `test -f 'parametermodbusieee754matrix.cpp' || echo '$(srcdir)/'`parametermodbusieee754matrix.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbusieee754matrix.Tpo $(DEPDIR)/bigbrother-parametermodbusieee754matrix.Po
#	$(AM_V_CXX)source='parametermodbusieee754matrix.cpp' object='bigbrother-parametermodbusieee754matrix.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbusieee754matrix.o `test -f 'parametermodbusieee754matrix.cpp' || echo '$(srcdir)/'`parametermodbusieee754matrix.cpp

bigbrother-parametermodbusieee754matrix.obj: parametermodbusieee754matrix.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-parametermodbusieee754matrix.obj -MD -MP -MF $(DEPDIR)/bigbrother-parametermodbusieee754matrix.Tpo -c -o bigbrother-parametermodbusieee754matrix.obj `if test -f 'parametermodbusieee754matrix.cpp'; then $(CYGPATH_W) 'parametermodbusieee754matrix.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbusieee754matrix.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-parametermodbusieee754matrix.Tpo $(DEPDIR)/bigbrother-parametermodbusieee754matrix.Po
#	$(AM_V_CXX)source='parametermodbusieee754matrix.cpp' object='bigbrother-parametermodbusieee754matrix.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-parametermodbusieee754matrix.obj `if test -f 'parametermodbusieee754matrix.cpp'; then $(CYGPATH_W) 'parametermodbusieee754matrix.cpp'; else $(CYGPATH_W) '$(srcdir)/parametermodbusieee754matrix.cpp'; fi`

bigbrother-server.o: server.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-server.o -MD -MP -MF $(DEPDIR)/bigbrother-server.Tpo -c -o bigbrother-server.o `test -f 'server.cpp' || echo '$(srcdir)/'`server.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-server.Tpo $(DEPDIR)/bigbrother-server.Po
#	$(AM_V_CXX)source='server.cpp' object='bigbrother-server.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-server.o `test -f 'server.cpp' || echo '$(srcdir)/'`server.cpp

bigbrother-server.obj: server.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-server.obj -MD -MP -MF $(DEPDIR)/bigbrother-server.Tpo -c -o bigbrother-server.obj `if test -f 'server.cpp'; then $(CYGPATH_W) 'server.cpp'; else $(CYGPATH_W) '$(srcdir)/server.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-server.Tpo $(DEPDIR)/bigbrother-server.Po
#	$(AM_V_CXX)source='server.cpp' object='bigbrother-server.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-server.obj `if test -f 'server.cpp'; then $(CYGPATH_W) 'server.cpp'; else $(CYGPATH_W) '$(srcdir)/server.cpp'; fi`

bigbrother-curlwrapper.o: curlwrapper.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-curlwrapper.o -MD -MP -MF $(DEPDIR)/bigbrother-curlwrapper.Tpo -c -o bigbrother-curlwrapper.o `test -f 'curlwrapper.cpp' || echo '$(srcdir)/'`curlwrapper.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-curlwrapper.Tpo $(DEPDIR)/bigbrother-curlwrapper.Po
#	$(AM_V_CXX)source='curlwrapper.cpp' object='bigbrother-curlwrapper.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-curlwrapper.o `test -f 'curlwrapper.cpp' || echo '$(srcdir)/'`curlwrapper.cpp

bigbrother-curlwrapper.obj: curlwrapper.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-curlwrapper.obj -MD -MP -MF $(DEPDIR)/bigbrother-curlwrapper.Tpo -c -o bigbrother-curlwrapper.obj `if test -f 'curlwrapper.cpp'; then $(CYGPATH_W) 'curlwrapper.cpp'; else $(CYGPATH_W) '$(srcdir)/curlwrapper.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-curlwrapper.Tpo $(DEPDIR)/bigbrother-curlwrapper.Po
#	$(AM_V_CXX)source='curlwrapper.cpp' object='bigbrother-curlwrapper.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-curlwrapper.obj `if test -f 'curlwrapper.cpp'; then $(CYGPATH_W) 'curlwrapper.cpp'; else $(CYGPATH_W) '$(srcdir)/curlwrapper.cpp'; fi`

bigbrother-UMKA03utilites.o: UMKA03utilites.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-UMKA03utilites.o -MD -MP -MF $(DEPDIR)/bigbrother-UMKA03utilites.Tpo -c -o bigbrother-UMKA03utilites.o `test -f 'UMKA03utilites.cpp' || echo '$(srcdir)/'`UMKA03utilites.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-UMKA03utilites.Tpo $(DEPDIR)/bigbrother-UMKA03utilites.Po
#	$(AM_V_CXX)source='UMKA03utilites.cpp' object='bigbrother-UMKA03utilites.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-UMKA03utilites.o `test -f 'UMKA03utilites.cpp' || echo '$(srcdir)/'`UMKA03utilites.cpp

bigbrother-UMKA03utilites.obj: UMKA03utilites.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-UMKA03utilites.obj -MD -MP -MF $(DEPDIR)/bigbrother-UMKA03utilites.Tpo -c -o bigbrother-UMKA03utilites.obj `if test -f 'UMKA03utilites.cpp'; then $(CYGPATH_W) 'UMKA03utilites.cpp'; else $(CYGPATH_W) '$(srcdir)/UMKA03utilites.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-UMKA03utilites.Tpo $(DEPDIR)/bigbrother-UMKA03utilites.Po
#	$(AM_V_CXX)source='UMKA03utilites.cpp' object='bigbrother-UMKA03utilites.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-UMKA03utilites.obj `if test -f 'UMKA03utilites.cpp'; then $(CYGPATH_W) 'UMKA03utilites.cpp'; else $(CYGPATH_W) '$(srcdir)/UMKA03utilites.cpp'; fi`

bigbrother-PostToServer.o: PostToServer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-PostToServer.o -MD -MP -MF $(DEPDIR)/bigbrother-PostToServer.Tpo -c -o bigbrother-PostToServer.o `test -f 'PostToServer.cpp' || echo '$(srcdir)/'`PostToServer.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-PostToServer.Tpo $(DEPDIR)/bigbrother-PostToServer.Po
#	$(AM_V_CXX)source='PostToServer.cpp' object='bigbrother-PostToServer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-PostToServer.o `test -f 'PostToServer.cpp' || echo '$(srcdir)/'`PostToServer.cpp

bigbrother-PostToServer.obj: PostToServer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-PostToServer.obj -MD -MP -MF $(DEPDIR)/bigbrother-PostToServer.Tpo -c -o bigbrother-PostToServer.obj `if test -f 'PostToServer.cpp'; then $(CYGPATH_W) 'PostToServer.cpp'; else $(CYGPATH_W) '$(srcdir)/PostToServer.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-PostToServer.Tpo $(DEPDIR)/bigbrother-PostToServer.Po
#	$(AM_V_CXX)source='PostToServer.cpp' object='bigbrother-PostToServer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-PostToServer.obj `if test -f 'PostToServer.cpp'; then $(CYGPATH_W) 'PostToServer.cpp'; else $(CYGPATH_W) '$(srcdir)/PostToServer.cpp'; fi`

bigbrother-DataTransfer.o: DataTransfer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-DataTransfer.o -MD -MP -MF $(DEPDIR)/bigbrother-DataTransfer.Tpo -c -o bigbrother-DataTransfer.o `test -f 'DataTransfer.cpp' || echo '$(srcdir)/'`DataTransfer.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-DataTransfer.Tpo $(DEPDIR)/bigbrother-DataTransfer.Po
#	$(AM_V_CXX)source='DataTransfer.cpp' object='bigbrother-DataTransfer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-DataTransfer.o `test -f 'DataTransfer.cpp' || echo '$(srcdir)/'`DataTransfer.cpp

bigbrother-DataTransfer.obj: DataTransfer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-DataTransfer.obj -MD -MP -MF $(DEPDIR)/bigbrother-DataTransfer.Tpo -c -o bigbrother-DataTransfer.obj `if test -f 'DataTransfer.cpp'; then $(CYGPATH_W) 'DataTransfer.cpp'; else $(CYGPATH_W) '$(srcdir)/DataTransfer.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-DataTransfer.Tpo $(DEPDIR)/bigbrother-DataTransfer.Po
#	$(AM_V_CXX)source='DataTransfer.cpp' object='bigbrother-DataTransfer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-DataTransfer.obj `if test -f 'DataTransfer.cpp'; then $(CYGPATH_W) 'DataTransfer.cpp'; else $(CYGPATH_W) '$(srcdir)/DataTransfer.cpp'; fi`

bigbrother-OverflowFile.o: OverflowFile.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-OverflowFile.o -MD -MP -MF $(DEPDIR)/bigbrother-OverflowFile.Tpo -c -o bigbrother-OverflowFile.o `test -f 'OverflowFile.cpp' || echo '$(srcdir)/'`OverflowFile.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-OverflowFile.Tpo $(DEPDIR)/bigbrother-OverflowFile.Po
#	$(AM_V_CXX)source='OverflowFile.cpp' object='bigbrother-OverflowFile.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-OverflowFile.o `test -f 'OverflowFile.cpp' || echo '$(srcdir)/'`OverflowFile.cpp

bigbrother-OverflowFile.obj: OverflowFile.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-OverflowFile.obj -MD -MP -MF $(DEPDIR)/bigbrother-OverflowFile.Tpo -c -o bigbrother-OverflowFile.obj `if test -f 'OverflowFile.cpp'; then $(CYGPATH_W) 'OverflowFile.cpp'; else $(CYGPATH_W) '$(srcdir)/OverflowFile.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-OverflowFile.Tpo $(DEPDIR)/bigbrother-OverflowFile.Po
#	$(AM_V_CXX)source='OverflowFile.cpp' object='bigbrother-OverflowFile.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-OverflowFile.obj `if test -f 'OverflowFile.cpp'; then $(CYGPATH_W) 'OverflowFile.cpp'; else $(CYGPATH_W) '$(srcdir)/OverflowFile.cpp'; fi`

bigbrother-ConfigFile.o: ConfigFile.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-ConfigFile.o -MD -MP -MF $(DEPDIR)/bigbrother-ConfigFile.Tpo -c -o bigbrother-ConfigFile.o `test -f 'ConfigFile.cpp' || echo '$(srcdir)/'`ConfigFile.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-ConfigFile.Tpo $(DEPDIR)/bigbrother-ConfigFile.Po
#	$(AM_V_CXX)source='ConfigFile.cpp' object='bigbrother-ConfigFile.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-ConfigFile.o `test -f 'ConfigFile.cpp' || echo '$(srcdir)/'`ConfigFile.cpp

bigbrother-ConfigFile.obj: ConfigFile.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-ConfigFile.obj -MD -MP -MF $(DEPDIR)/bigbrother-ConfigFile.Tpo -c -o bigbrother-ConfigFile.obj `if test -f 'ConfigFile.cpp'; then $(CYGPATH_W) 'ConfigFile.cpp'; else $(CYGPATH_W) '$(srcdir)/ConfigFile.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-ConfigFile.Tpo $(DEPDIR)/bigbrother-ConfigFile.Po
#	$(AM_V_CXX)source='ConfigFile.cpp' object='bigbrother-ConfigFile.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-ConfigFile.obj `if test -f 'ConfigFile.cpp'; then $(CYGPATH_W) 'ConfigFile.cpp'; else $(CYGPATH_W) '$(srcdir)/ConfigFile.cpp'; fi`

bigbrother-XMLAttribute.o: XMLAttribute.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-XMLAttribute.o -MD -MP -MF $(DEPDIR)/bigbrother-XMLAttribute.Tpo -c -o bigbrother-XMLAttribute.o `test -f 'XMLAttribute.cpp' || echo '$(srcdir)/'`XMLAttribute.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-XMLAttribute.Tpo $(DEPDIR)/bigbrother-XMLAttribute.Po
#	$(AM_V_CXX)source='XMLAttribute.cpp' object='bigbrother-XMLAttribute.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-XMLAttribute.o `test -f 'XMLAttribute.cpp' || echo '$(srcdir)/'`XMLAttribute.cpp

bigbrother-XMLAttribute.obj: XMLAttribute.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -MT bigbrother-XMLAttribute.obj -MD -MP -MF $(DEPDIR)/bigbrother-XMLAttribute.Tpo -c -o bigbrother-XMLAttribute.obj `if test -f 'XMLAttribute.cpp'; then $(CYGPATH_W) 'XMLAttribute.cpp'; else $(CYGPATH_W) '$(srcdir)/XMLAttribute.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bigbrother-XMLAttribute.Tpo $(DEPDIR)/bigbrother-XMLAttribute.Po
#	$(AM_V_CXX)source='XMLAttribute.cpp' object='bigbrother-XMLAttribute.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(bigbrother_CPPFLAGS) $(CPPFLAGS) $(bigbrother_CXXFLAGS) $(CXXFLAGS) -c -o bigbrother-XMLAttribute.obj `if test -f 'XMLAttribute.cpp'; then $(CYGPATH_W) 'XMLAttribute.cpp'; else $(CYGPATH_W) '$(srcdir)/XMLAttribute.cpp'; fi`

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
		-rm -f ./$(DEPDIR)/bigbrother-ConfigFile.Po
	-rm -f ./$(DEPDIR)/bigbrother-DataTransfer.Po
	-rm -f ./$(DEPDIR)/bigbrother-Din16Dout8.Po
	-rm -f ./$(DEPDIR)/bigbrother-EngineModbus.Po
	-rm -f ./$(DEPDIR)/bigbrother-EngineModbusRTU.Po
	-rm -f ./$(DEPDIR)/bigbrother-EngineModbusTCP.Po
	-rm -f ./$(DEPDIR)/bigbrother-EngineModbusTCPServer.Po
	-rm -f ./$(DEPDIR)/bigbrother-KN24defs.Po
	-rm -f ./$(DEPDIR)/bigbrother-OverflowFile.Po
	-rm -f ./$(DEPDIR)/bigbrother-ParameterModbusFileKN24.Po
	-rm -f ./$(DEPDIR)/bigbrother-PostToServer.Po
	-rm -f ./$(DEPDIR)/bigbrother-QueryMsg.Po
	-rm -f ./$(DEPDIR)/bigbrother-UMKA03utilites.Po
	-rm -f ./$(DEPDIR)/bigbrother-XMLAttribute.Po
	-rm -f ./$(DEPDIR)/bigbrother-curlwrapper.Po
	-rm -f ./$(DEPDIR)/bigbrother-device.Po
	-rm -f ./$(DEPDIR)/bigbrother-deviceShunt.Po
	-rm -f ./$(DEPDIR)/bigbrother-devicemodbus.Po
	-rm -f ./$(DEPDIR)/bigbrother-devicemodemstat.Po
	-rm -f ./$(DEPDIR)/bigbrother-globals.Po
	-rm -f ./$(DEPDIR)/bigbrother-main.Po
	-rm -f ./$(DEPDIR)/bigbrother-modem.Po
	-rm -f ./$(DEPDIR)/bigbrother-parameter.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbus.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbusbool.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbusenum.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbusfile.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbusieee754.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbusieee754array.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbusieee754matrix.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbusint.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbusws.Po
	-rm -f ./$(DEPDIR)/bigbrother-port.Po
	-rm -f ./$(DEPDIR)/bigbrother-portsettings.Po
	-rm -f ./$(DEPDIR)/bigbrother-scada.Po
	-rm -f ./$(DEPDIR)/bigbrother-semaphors.Po
	-rm -f ./$(DEPDIR)/bigbrother-server.Po
	-rm -f ./$(DEPDIR)/bigbrother-utilites.Po
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
		-rm -f ./$(DEPDIR)/bigbrother-ConfigFile.Po
	-rm -f ./$(DEPDIR)/bigbrother-DataTransfer.Po
	-rm -f ./$(DEPDIR)/bigbrother-Din16Dout8.Po
	-rm -f ./$(DEPDIR)/bigbrother-EngineModbus.Po
	-rm -f ./$(DEPDIR)/bigbrother-EngineModbusRTU.Po
	-rm -f ./$(DEPDIR)/bigbrother-EngineModbusTCP.Po
	-rm -f ./$(DEPDIR)/bigbrother-EngineModbusTCPServer.Po
	-rm -f ./$(DEPDIR)/bigbrother-KN24defs.Po
	-rm -f ./$(DEPDIR)/bigbrother-OverflowFile.Po
	-rm -f ./$(DEPDIR)/bigbrother-ParameterModbusFileKN24.Po
	-rm -f ./$(DEPDIR)/bigbrother-PostToServer.Po
	-rm -f ./$(DEPDIR)/bigbrother-QueryMsg.Po
	-rm -f ./$(DEPDIR)/bigbrother-UMKA03utilites.Po
	-rm -f ./$(DEPDIR)/bigbrother-XMLAttribute.Po
	-rm -f ./$(DEPDIR)/bigbrother-curlwrapper.Po
	-rm -f ./$(DEPDIR)/bigbrother-device.Po
	-rm -f ./$(DEPDIR)/bigbrother-deviceShunt.Po
	-rm -f ./$(DEPDIR)/bigbrother-devicemodbus.Po
	-rm -f ./$(DEPDIR)/bigbrother-devicemodemstat.Po
	-rm -f ./$(DEPDIR)/bigbrother-globals.Po
	-rm -f ./$(DEPDIR)/bigbrother-main.Po
	-rm -f ./$(DEPDIR)/bigbrother-modem.Po
	-rm -f ./$(DEPDIR)/bigbrother-parameter.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbus.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbusbool.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbusenum.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbusfile.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbusieee754.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbusieee754array.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbusieee754matrix.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbusint.Po
	-rm -f ./$(DEPDIR)/bigbrother-parametermodbusws.Po
	-rm -f ./$(DEPDIR)/bigbrother-port.Po
	-rm -f ./$(DEPDIR)/bigbrother-portsettings.Po
	-rm -f ./$(DEPDIR)/bigbrother-scada.Po
	-rm -f ./$(DEPDIR)/bigbrother-semaphors.Po
	-rm -f ./$(DEPDIR)/bigbrother-server.Po
	-rm -f ./$(DEPDIR)/bigbrother-utilites.Po
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--depfiles check check-am clean \
	clean-binPROGRAMS clean-generic cscopelist-am ctags ctags-am \
	distclean distclean-compile distclean-generic distclean-tags \
	distdir dvi dvi-am html html-am info info-am install \
	install-am install-binPROGRAMS install-data install-data-am \
	install-dvi install-dvi-am install-exec install-exec-am \
	install-html install-html-am install-info install-info-am \
	install-man install-pdf install-pdf-am install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic pdf pdf-am \
	ps ps-am tags tags-am uninstall uninstall-am \
	uninstall-binPROGRAMS

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
